sudo: false

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=0

matrix:
  include:
    - name: PHPCS
      php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=0 PHPCS=1
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.4snapshot
      env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=5.7.*"
  - |
    if [[ "$PHPCS" == "1" ]]; then
      composer global require dealerdirect/phpcodesniffer-composer-installer
      composer global require wp-coding-standards/wpcs
      composer global require automattic/vipwpcs
      composer global require phpcompatibility/phpcompatibility-wp
    fi

script:
  - |
    if [[ "$PHPCS" == "1" ]]; then
      phpcs -s --extensions=php,js .
    fi
  - |
    if [[ "$PHPCS" != "1" ]]; then
      phpunit
    fi
