name: End To End Tests

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  testing:
    name: Playwright Tests

    runs-on: ubuntu-latest

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Run Playwright tests
      uses: polylang/actions/e2e@main
